learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views


# This is for template tagging for relative urls
app_name = 'basicapp'

urlpatterns = [
    # $ sign means for anything after relative or other
    url(r'relative/$',views.relative, name='relative'),
    url(r'other/$',views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url('admin/', admin.site.urls),
    url(r'basicapp/', include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basicapp/index.html',context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <ul clas= "nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin page</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">Other page</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'basicapp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index page in the app</a>

  </body>
</html>